name: MacOS build

on: [push, pull_request]

jobs:
  macos-build:
    name: MacOS build
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          auto-update-conda: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mkdir build
          conda update -n base -c defaults conda
          conda install -c conda-forge cmake ninja -y
          conda install -c conda-forge --yes --quiet pdal -y

      - name: Run cmake
        shell: bash -l {0}
        working-directory: ./build
        run: |
          cmake -G Ninja \
            -DCMAKE_FIND_FRAMEWORK="NEVER" \
            -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
            ..

      - name: Build pdal_wrench
        shell: bash -l {0}
        working-directory: ./build
        run: |
          ninja
          ninja install
